name: name-date
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.10
  - cudatoolkit=11.6
  - tqdm
  - numpy=1.23
  - matplotlib
  - pip
  - pip:
      - torch==1.12.1
      - torchvision==0.13.1
      - torchinfo
