name: name-date
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.10
  - cudatoolkit
  - tqdm
  - numpy
  - matplotlib
  - pip
  - pip:
      - torch
      - torchvision
      - torchinfo
